### PR TITLE
Added :rename-to and :rename-column-to for :alter-table

### PR DESCRIPTION
**Pull request by knobo**

### CODE REVIEW

**Comment by knobo** [comment]
``` cl
(sql (:alter-table "mytable" :rename-to "newtable"))
"ALTER TABLE mytable RENAME TO newtable"

(sql (:alter-table :my-table :rename-to :new-table))
"ALTER TABLE my_table RENAME TO new_table"
```

**Comment by sabracrolleton** [comment]
I would request that your patch handle renaming a column as well as renaming the table itself.

**Comment by knobo** [comment]
Would you also accept something like alter-sequence function:

https://gist.github.com/knobo/6beb0ab71b8bbe182afc5ffee5b7e69f#file-s-sql-lisp

**Comment by knobo** [comment]
Do you have any suggestion on :rename-to, maybe it should be :rename-table-to?

**Comment by knobo** [comment]
To test it:

``` cl
(with-schema ("testing_rename" :drop-after t)
      (query (:create-table  :testing ((:main :type int :primary-key t))))
      (query (:alter-table :testing :rename-column-to :main :id))
      (query (:alter-table :testing :rename-to :success))
      (table-description :success))
```

**Comment by knobo** [comment]
Maybe it should be :rename and :rename-column, and skip the "-to" part?

**Comment by sabracrolleton** [comment]
I am comfortable with :rename and :rename-column

**Comment by sabracrolleton** [comment]
Your requested additions have been included in the most recent update.

**Pull request closed without merging**
