### PR TITLE
Make it compilable by clasp, fix missing conditionalisation in query.lis

### PR DESCRIPTION
**Pull request by kpoeck**
With the change testsuite says:
```lisp
 Did 317 checks.
    Pass: 314 (99%)
    Skip: 0 ( 0%)
    Fail: 3 ( 0%)
````

### CODE REVIEW

**Comment by kpoeck** [comment]
The errors are ort of strange since al output seems to e equalp:
```lisp
 Failure Details:
 --------------------------------
 SAVE-DAO []: 
      
'(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
  ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0)))

 evaluated to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0)))

 which is not 

EQUALP

 to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0)))

..
 --------------------------------
 --------------------------------
 SAVE-DAO []: 
      
'(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
  ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
  ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0)))

 evaluated to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0)))

 which is not 

EQUALP

 to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0)))

..
 --------------------------------
 --------------------------------
 SAVE-DAO []: 
      
'(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
  ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
  ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0))
  ((:ID . 4) (:A . "D string") (:B) (:C . 14) (:D . 939/50)))

 evaluated to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0))
 ((:ID . 4) (:A . "D string") (:B) (:C . 14) (:D . 939/50)))

 which is not 

EQUALP

 to 

(((:ID . 1) (:A . "bar") (:B) (:C . 0) (:D . 0))
 ((:ID . 2) (:A . "first short") (:B) (:C . 0) (:D . 0))
 ((:ID . 3) (:A . "12.75") (:B) (:C . 0) (:D . 0))
 ((:ID . 4) (:A . "D string") (:B) (:C . 14) (:D . 939/50)))
````

**Comment by sabracrolleton** [comment]
Hmmm. Do not have those errors under sbcl, ccl, ecl or cmucl, I know abcl has problems with daos that I have not been able to resolve, but it is not clear that those are related. Does clasp work with v.7 or 8 of llvm and clang?

**Comment by kpoeck** [comment]
clasp works with v6 of llvm

**Comment by kpoeck** [comment]
but I believe the changes aer obvious, the 3 failing tests ae just an additional challenge having nothing to do with my pull-request

**Pull request merged**
