### PR TITLE
programatically export all cl-postgres-oid symbols

### PR DESCRIPTION
**Pull request by slyrus**
NOTE!!! I'm not sure if this is really worth doing, but since I rigged it up, I figured I'd put it here for examination. Let me know what you think.

 * cl-postgres-oid no longer uses :common-lisp (or any other packages),
   so all of the symbols in it are oid symbols.

 * iterate over the symbols and export them at the end of oid.lisp.

 * unexport all of the oid symbols, if present, prior to the defpackage
   form so we don't get warnings on reloading of the package.lisp file.

### CODE REVIEW

**Comment by PuercoPop** [comment]
If the goal is the avoid writing the symbols in the package definition wouldn't an easier approach be to define a macro, define-oid, that expands into a defconstant + a call to export? Am I misunderstanding the issue?

**Comment by slyrus** [comment]
Yeah, that would work too. Not clear that it's easier but it would have the same effect, I suppose.

**Comment by slyrus** [comment]
Without that loop, SBCL complains if you re-eval the defpackage form. Like I said, we can do this, I'm not sure we should :) It's probably better the way it is now.

**Comment by marijnh** [comment]
Yeah, that's a bit scary. Let's leave the duplicate lists in then.

**Pull request closed without merging**
