### PR TITLE
Fix bug and switch variable names in reader-for-format

### PR DESCRIPTION
**Pull request by asciinen**

### CODE REVIEW

**Comment by sabracrolleton** [comment]
Can you include a test case patch to postmodern/tests.lisp?

**Comment by asciinen** [comment]
> Can you include a test case patch to
> postmodern/tests.lisp?

I'm not sure I understand what you mean. A test case to
demonstrate the bug?

The function I changed had been correct once, but was
recently changed to make it thread-safe, and it seems to me
that through a simple oversight the code got messed up. One
result is that the macro that uses it produces code with an
undefined variable ("CLASS"); that's how I noticed it:

(pomo:query "select a,b,c from foo" (:dao foo))

is expanded to:

(POSTMODERN::ALL-ROWS
 (CL-POSTGRES:EXEC-QUERY
   POSTMODERN:*DATABASE* "select a,b,c from foo"
    (LET ((#:G1020 (FIND-CLASS 'FOO)))
      (UNLESS (SB-MOP:CLASS-FINALIZED-P CLASS)
        (UNLESS (SB-MOP:CLASS-FINALIZED-P #:G1020)
          (BORDEAUX-THREADS:WITH-LOCK-HELD (POSTMODERN::*CLASS-FINALIZE-LOCK*)
            (UNLESS (SB-MOP:CLASS-FINALIZED-P #:G1020)
              (SB-MOP:FINALIZE-INHERITANCE #:G1020)))))
      (POSTMODERN::DAO-ROW-READER #:G1020))))

**Comment by asciinen** [comment]
> What I was asking for was for you to add an additional
> fivam test showing that the function (as corrected by you)
> works. It helps ensure future edits do not screw up what
> you just corrected.

I'm afraid I'm not competent enough. I wouldn't know how to
write a test for both #+postmodern-thread-safe and
#-postmodern-thread-safe

Secondly, I wouldn't know how to write a test (a least a
simple and readable one) to prove that the function was
indeed thread-safe.

Sorry.

By the way, do you know if it is possible to change the
behaviour of postmodern, so that a NULL value in the table
produced a NIL on the lisp side (instead of the :null
symbol), and a NIL value would be written as a NULL, instead
of false? The current behaviour, though it makes sense for
columns with type “boolean”, is out-of-tune with lisp (NULL
being true), and requires verbose and error-prone code in
most cases. Furthermore, it leads to the following
irregularity in case of columns with type "text":

  if a (text-typed) slot's value is NIL, the string "false"
  will be written in the database. It will then be retrieved
  as the string "false", not NIL.

  Thus, read(write(NIL)) != NIL

After a cursory look at the code (and perusal of the
documentation), I could not figure out if this behavior was
under the library user's control. Maybe I missed something
simple? I'd be grateful for any hint.

Pawel

**Comment by sabracrolleton** [comment]
I agree with you that writing the string "false" into a text column is an issue and violates the principle of least surprise. I have been bitten by it as well. A variation of the question was raised back in July 2013 on the mailing list and Marijn decided not to accept the solution offered at that time.  https://mailman.common-lisp.net/pipermail/postmodern-devel/2013-July/000812.html. 

I will add it to the enhancement request list and see what I can do.

**Comment by asciinen** [comment]
Thank you for the explanation!

Pawel

**Pull request merged**
