### PR TITLE
fix array of null handling

### PR DESCRIPTION
**Pull request by slyrus**
* fixes handling of arrays with null elmemts

 * also, return nil two places where we used to return :null

### CODE REVIEW

**Comment by slyrus** [comment]
@marijnh do you have any preference on returning nil vs :null ? I'm not sure what the right thing to do here is. thanks!

**Comment by marijnh** [comment]
We're representing SQL null as `:null`. That's how the library is documented and that's what it should continue doing.

**Comment by slyrus** [comment]
Ok, my mistake. Thanks!

**Comment by slyrus** [comment]
How do you feel about the zero length arrays? nil, (make-array nil) or (make-array nil) or (make-array 0)?

**Comment by marijnh** [comment]
Zero-length arrays would be an array of length zero. (Zero-dimension arrays, I have no idea. Does it matter? Does anyone create those?)

**Comment by slyrus** [comment]
They are a lisp language-lawyer-inspired oddity. I ask because the thing we're getting back from PG is actually a zero dimension array, which, theoretically, maps more closely to a (make-array nil), but we'll probably just annoy our users if we actually return one of those.

**Comment by slyrus** [comment]
And @sebyte's original bug was caused by the fact that I was checking for 1-d, 0 length arrays, but not 0-d arrays back from pg. Of course that bug helped uncover lots of other things that needed to be fixed.

**Comment by marijnh** [comment]
Great. Merged as 160ba03

**Pull request closed without merging**
