### PR TITLE
Create database

### PR DESCRIPTION
**Pull request by Symbolics**
This pull request does not contain updates to the documentation. What is the best way to do this? Are the docs hand-edited HTML?

### CODE REVIEW

**Comment by sabracrolleton** [comment]
The docs are hand-edited html, so I would suggest adding the new documentation language to the docs/s-sql.html file  and include that in the pull request. I am currently testing some changes I will propose for adding on-conflict functionality to insert-into which will require appropriate changes to the docs. Note: I am not the maintainer.

**Comment by Symbolics** [comment]
Cheers for that @sabracrolleton. I notice that you have a collection of utilities for Postmodern that look useful. Do you know if there is a plan to incorporate these into the repository?

**Comment by sabracrolleton** [comment]
I do not know who really has the lead role on postmodern these days. I am
also not aware of any long term planning. I would like to make some of the
newer postgresql functionality more accessible, but I think it will take a
substantial amount of time before I could pull together a long term
proposal for whoever is the current lead on the project.

**Comment by marijnh** [comment]
There's no active maintainer. I'll merge pull requests now and then but I would be really glad if someone took over the project.

**Comment by Symbolics** [comment]
Documentation added.

**Comment by Symbolics** [comment]
sql-op :create-database now has options provided by postgresql

**Pull request merged**
