### PR TITLE
Add application-name

### PR DESCRIPTION
**Pull request by samuel-jimenez**
Allow setting application name via connect

### CODE REVIEW

**Comment by sabracrolleton** [comment]
What is the purpose?

**Comment by samuel-jimenez** [comment]
I tried to keep it as simple as I could. You can set the application name by using the :application-name key with postmodern:connect , or a new optional parameter to cl-postgres:open-database. The default is an empty string, so it should not interfere with testing.

**Comment by sabracrolleton** [comment]
FYI: I just added doc amendments and one test case.

**Comment by samuel-jimenez** [comment]
It looks good to me. Thanks!

**Pull request merged**
