### PR TITLE
Add file attributes for Genera

### PR DESCRIPTION
**Pull request by Symbolics**
Trivial, but necessary, change to support a clean load on Genera. Without a syntax attribute, CltL2 syntax is used and this has different enough syntax to abort the compile.

### CODE REVIEW

**Comment by sabracrolleton** [comment]
What is the merge branch doing in the pull request?

**Comment by Symbolics** [comment]
Master, but please wait. I have further changes to commit. See an email from a few days ago.

**Comment by sabracrolleton** [comment]
This proposed commit actually just changes some emacs local variables. Is this really a Postmodern issue or something in your emacs config dealing with Genera? I note that you had submitted the change that created that line back in November last year.

**Comment by Symbolics** [comment]
It is an unfortunate choice on the part of emacs to set its local variables with a very similar mechanism. This has nothing to do with emacs.  It is because Genera doesn't handle (in-package ...) the way that most people expect, but instead uses the Package file attribute to determine which package to place definitions into. Here's the note I put on a pull request for another package when asked about it:

Briefly, the attribute line sets certain properties of the file when it is read, and these are used when compiling and loading. For example 'Syntax' specifies one of the (at least) three dialects of LISP that Genera runs:
```lisp
LISP             -> ZetaLisp
COMMON-LISP      -> CLtL2
ANSI-COMMON-LISP -> ANSI LISP
```
A common problem is people putting COMMON-LISP (CltL2) in for Syntax. It's close enough that it will sometimes work, but often introduces subtle bugs. This is probably partly because emacs also uses this line to set some editing modes and people do not realize that they have real meaning to some compilers and are not just cosmetic.

The Package attribute is equivalent to (in-package). Genera honors (in-package), but not until _after_ compiling and loading the file using the Package attribute. If the Package attribute wasn't set, it uses the current package, which is often the last file compiled, so you end up with all the definitions being loaded into packages off by one. There is an open bug for this, as the ANSI spec says compile & load should rebind `*package*` & `*read-table*` to the values they had before processing the file.

Fortunately the fix is easily made by adding syntax and package attributes in the file attribute line throughout the project.

**Comment by Symbolics** [comment]
> 
> 
> What is the merge branch doing in the pull request?

Apologies, just read (and understood) this question. It's there because I'm still learning git. I'll fix this up into a single commit.

**Comment by Symbolics** [comment]
I've cleaned up and committed the file attribute changes. Summary:

- **No changes to executable code**
- ASDF/Packages slightly refactored, continuing along the lines of previous work (package.lisp, et. al.)
- Add an attribute line added as a comment to the top of each file

Explanation of changes: the first pull request added a Syntax attribute for s-sql.lisp so that it would _compile_. However whilst running the tests, I discovered that without the Package attribute, symbols end up in the wrong package, and of course that doesn't work very well. The comment lines at the top of the files ensure everything ends up in the correct place and compiles correctly.

Tests run in SBCL and CCL the same before and after the changes. I've also updated the latest commit message with the reasons for the change, so if anyone 'git blames' me for the changes they'll know why they were necessary.

**Pull request merged**
